version: "3.6"
services:
  arango:
    image: arangodb:3.3
    environment:
      ARANGO_NO_AUTH: 1
  node:
    image: node:10-alpine
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    environment:
      DB_HOST: "arango"
      DB_PORT: 8529
      DB_NAME: "sandbox"
    command: /opt/app/node_modules/.bin/forever --watch --spinSLeepTime=5000 --minUptime=100 --watchDirectory=/opt/app/lib /opt/app/test.js
